lines 25
columns 80

edge top
background_opacity 0.66
hide_on_focus_loss yes

margin_left 0
margin_right 0
margin_top 0
margin_bottom 0

# output_name LG Electronics UltraFine Pro 107NTEP53804 (DP-5)

output_name desc:LG Electronics UltraFine Pro 107NTEP53804

app_id kitty-quick-access


