# Clipse clipboard manager configuration

exec-once = clipse -listen # run listener on startup

windowrule = match:class clipse, float true # ensure you have a floating window class set if you want this behavior
windowrule = match:class clipse, size 622 652 # set the size of the window as necessary

bind = SUPER, V, exec,  kitty --class clipse -e 'clipse'

# Example: bind = SUPER, V, exec, alacritty --class clipse -e 'clipse'
