##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

$hyper = SUPER SHIFT ALT CTRL

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = sone-borderless
    match:class = ^(sone)$
    border_size = 0
    rounding = 0
}


# HyprMod managed settings
source = /home/janis/.config/hypr/hyprland-gui.conf

# JR Persistent Workspace-Rules
workspace = 1, monitor:desc:LG Electronics LG ULTRAWIDE 0x000850EB, persistent:true, default:true
workspace = 2, monitor:desc:LG Electronics LG ULTRAWIDE 0x000850EB,
workspace = 3, monitor:desc:LG Electronics LG ULTRAWIDE 0x000850EB,
workspace = 4, monitor:desc:LG Electronics LG ULTRAWIDE 0x000850EB,

workspace = 5, monitor:desc:LG Electronics UltraFine Pro 107NTEP53804, persistent:true, default:true
workspace = 6, monitor:desc:LG Electronics UltraFine Pro 107NTEP53804,
workspace = 7, monitor:desc:LG Electronics UltraFine Pro 107NTEP53804,
workspace = 8, monitor:desc:LG Electronics UltraFine Pro 107NTEP53804,
workspace = 9, monitor:desc:LG Electronics UltraFine Pro 107NTEP53804,
workspace = 10, monitor:desc:LG Electronics UltraFine Pro 107NTEP53804,

# Hyprland per Workspace Layout
workspace = 8, layout:scrolling
workspace = 9, layout:scrolling
workspace = 10, layout:scrolling

# Apps to always open on specific workspaces
# Workspace 8
windowrule = workspace 8, match:class ^(whatsdesk)$
windowrule = workspace 8, match:class ^(vesktop)$
windowrule = workspace 8, match:class ^(org.telegram.desktop)$

# Special workspace
# windowrule = workspace special silent, match:class ^(obsidian)$ # Something doesn't quite work yet. 

# Creates a special kitty terminal workspace that can be tooggled with the keybind below
bind = $hyper, K, togglespecialworkspace, terminal # Keybind only here because it's closely tied to the below workspace rule
bind = $mainMod, T, togglespecialworkspace, terminal # Keybind only here because it's closely tied to the below workspace rule
exec-once = [workspace special:terminal silent] kitty --title scratchpad
windowrule = match:title ^(scratchpad)$, float on, center on, size 1400 900

# Float + center specific apps. Things like file pickers or settings dialogs that look better floating:
windowrule = match:class ^(org\.pulseaudio\.pavucontrol)$, float on, center on, size 800 600
windowrule = match:class ^(io.github.kaii_lb.Overskride)$, float on, center on, size 800 600
windowrule = match:class ^(kvantummanager)$, float on, center on, size 800 600
windowrule = match:class ^(nm-connection-editor)$, float on, center on, size 800 600

# Vicinae windowrules
layerrule = blur on, ignore_alpha 0, match:namespace vicinae
layerrule = no_anim on, match:namespace vicinae
# Focus window on activation
misc {
    focus_on_activate = true
}

# Affinity Photo 2 windowrules
windowrule = no_blur on, match:class photo.exe
windowrule = opacity 1.0 override 1.0 override, match:class photo.exe
windowrule = no_dim on, match:class photo.exe
